# Generated by Django 5.0.7 on 2024-07-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpo',
            old_name='QTY',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='vpo',
            old_name='UOM',
            new_name='uom',
        ),
    ]
