# Generated by Django 5.0.7 on 2024-07-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pId',
            new_name='productId',
        ),
    ]
