# Generated by Django 5.0.7 on 2024-07-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpo',
            name='date_created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
