# Generated by Django 5.0.7 on 2024-07-26 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vpo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpo',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
