# Generated by Django 5.0.7 on 2024-07-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vendor_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cusotmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerFirstName', models.CharField(max_length=100)),
                ('customerMiddleName', models.CharField(max_length=100)),
                ('customerLastName', models.CharField(max_length=100)),
                ('customerAddress', models.CharField(max_length=200)),
                ('customerPhoneNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
