# Generated by Django 5.0.7 on 2024-07-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cusotmer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cusotmer',
            new_name='Customer',
        ),
    ]
